export const venues = [
    {
        id:1,
        name:"Achilles Park, Tóparti Rendezvény és Üdülőpark",
        irsz:9012,
        megye:"Győr-Moson-Sopron vármegye",
        varos:"Gyirmóti Tájvédelmi Körzet",
        utca:"",
        hazszam:"",
        kapacitas:180,
        etel:1,
        bar:1,
        klima:1,
        tancter:200,
        parkolo:1,
        szallas:1,
        arkat:"szereny",
        megj:"Tópart",
        kep:"src/media/test_img/01.png",
        
    },
    {
        id:2,
        name:"Amstel Hattyú Fogadó",
        irsz:9025,
        megye:"Győr-Moson-Sopron vármegye",
        varos:"Győr",
        utca:"Töltésszer út",
        hazszam:"18.",
        kapacitas:200,
        etel:1,
        bar:0,
        klima:1,
        tancter:200,
        parkolo:1,
        szallas:0,
        arkat:"",
        megj:"Magyar- és nemzetközi konyha",
        kep:"src/media/test_img/05.png"


    },{
        id:3,
        name:"Sokoró Fogadó",
        irsz:9112,
        megye:"Győr-Moson-Sopron vármegye",
        varos:"Sokorópátka Főmajor",
        utca:"",
        hazszam:"",
        kapacitas:410,
        etel:1,
        bar:1,
        klima:0,
        tancter:450,
        parkolo:1,
        szallas:1,
        arkat:"",
        megj:"Lovaskocsikázás a Tájvédelmi Körzet területén",
        kep:"src/media/test_img/09.png"

    },{
        id:4,
        name:"Kristály Imperial Hotel",
        irsz:2890,
        megye:"Komárom-Esztergom vármegye",
        varos:"Tata",
        utca:"Ady Endre út",
        hazszam:"22.",
        kapacitas:620,
        etel:1,
        bar:1,
        klima:1,
        tancter:721,
        parkolo:1,
        szallas:1,
        arkat:"premium",
        megj:"Modern gasztronómia",
        kep:"src/media/test_img/13.png"

    },{
        id:5,
        name:"Öreg-tó Hotel és Rendezvénytér",
        irsz:2890,
        megye:"Komárom-Esztergom vármegye",
        varos:"Tata",
        utca:"Fáklya utca",
        hazszam:"4.",
        kapacitas:262,
        etel:1,
        bar:1,
        klima:1,
        tancter:341,
        parkolo:0,
        szallas:1,
        arkat:"átlagos",
        megj:"Élőzenés lehetőség",
        kep:"src/media/test_img/17.png"

    },{
        id:6,
        name:"Nádas Pihenőpark",
        irsz:2211,
        megye:"Pest vármegye",
        varos:"Vasad",
        utca:"Monori út",
        hazszam:"100.",
        kapacitas:860,
        etel:1,
        bar:1,
        klima:1,
        tancter:1225,
        parkolo:1,
        szallas:1,
        arkat:"premium",
        megj:"Kalandpark, horgászat, tófürdő",
        kep:"src/media/test_img/21.png"

    },{
        id:7,
        name:"Session Hotel Ráckeve",
        irsz:2300,
        megye:"Pest vármegye",
        varos:"Ráckeve",
        utca:"Termál sétány",
        hazszam:"1.",
        kapacitas:160,
        etel:1,
        bar:0,
        klima:0,
        tancter:410,
        parkolo:1,
        szallas:0,
        arkat:"szerény",
        megj:"Tánc show specialitások",
        kep:"src/media/test_img/25.png"

    },{
        id:8,
        name:"Jankovich Kúria Wellness Hotel",
        irsz:2459,
        megye:"Fejér vármegye",
        varos:"Rácalmás",
        utca:"Jankovich Miklós köz",
        hazszam:"1.",
        kapacitas:545,
        etel:1,
        bar:1,
        klima:1,
        tancter:740,
        parkolo:0,
        szallas:1,
        arkat:"Átlagos",
        megj:"Szoc-reál tanösvény",
        kep:"src/media/test_img/29.png"

    },{
        id:9,
        name:"Hunguest Hotel Pelion",
        irsz:8300,
        megye:"Veszprém vármegye",
        varos:"Tapolca",
        utca:"Köztársaság tér",
        hazszam:"10.",
        kapacitas:2090,
        etel:1,
        bar:1,
        klima:1,
        tancter:2000,
        parkolo:1,
        szallas:1,
        arkat:"premium",
        megj:"4 hektáros park, tenisz- és squash pályák",
        kep:"src/media/test_img/33.png"

    },
    
];